---
sudo: false
language: python
os:
  - linux
python:
  - "3.7"

git:
  depth: 2

cache: pip

branches:
  only:
  - master
  - devel
  - "/^\\d+\\.\\d+\\.\\d+[a]?\\d*$/"

env:
  global:
    - GITHUB_REPO=Midnighter/metanetx-sdk

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  fast_finish: true
  include:
  - stage: test
    install:
    - pip install --upgrade pip setuptools wheel tox tox-travis
    script:
    - tox -- --cov-report=xml
    after_success:
    - bash <(curl -f https://codecov.io/bash)
  - stage: deploy
    python: "3.7"
    install:
    - pip install --upgrade setuptools wheel
    script: skip
    deploy:
    - provider: pypi
      skip_cleanup: true
      distributions: sdist bdist_wheel
      user: $PYPI_USERNAME
      password: $PYPI_PASSWORD
      on:
        tags: true
        repo: $GITHUB_REPO
    - provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      body: "Please see https://github.com/${GITHUB_REPO}/blob/${TRAVIS_TAG}/CHANGELOG.rst for the full release notes."
      on:
        tags: true
        repo: $GITHUB_REPO

notifications:
  email:
    on_success: never
    on_failure: always
    on_pull_requests: never
